version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: order_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: ./.docker/api/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "50051:50051"
      - "8081:8081"

volumes:
  postgres_data:
    driver: local
